/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/opencv.hpp>
#include <stdio.h>

using namespace cv;
using namespace std;
/* Header for class com_netvirta_netvision_OpencvNativeClass */

#ifndef _Included_com_netvirta_netvision_OpencvNativeClass
#define _Included_com_netvirta_netvision_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_netvirta_netvision_OpencvNativeClass
 * Method:    convertGray
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_netvirta_netvision_OpencvNativeClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
