/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opencv2/opencv.hpp"
#include "opencv2/objdetect.hpp"
#include "opencv2/highgui.hpp"
#include "opencv2/imgproc.hpp"

#include <string>
#include <vector>

#include <android/log.h>
using namespace cv;

#ifndef _Included_com_netvirta_netvision_OpencvNativeClass
#define _Included_com_netvirta_netvision_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_netvirta_netvision_OpencvNativeClass
 * Method:    convertGray
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_netvirta_netvision_OpencvNativeClass_convertGray
        (JNIEnv *, jclass, jlong, jlong);

/**
 * Method to detect frame
 */
void detect(Mat &frame);

/*
 * Class:     com_netvirta_netvision_OpencvNativeClass
 * Method:    faceDetection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_netvirta_netvision_OpencvNativeClass_faceDetection
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_netvirta_netvision_OpencvNativeClass
 * Method:    bodyDetection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_netvirta_netvision_OpencvNativeClass_bodyDetection
        (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
